[versions]
android = "8.7.3"
apksig = "4.4.0"
bcpkix-jdk18on = "1.77"
kotlin = "2.0.21"
core-ktx = "1.15.0"

[libraries]
apksig = { module = "com.github.MuntashirAkon:apksig-android", version.ref = "apksig" }
bcpkix-jdk18on = { module = "org.bouncycastle:bcpkix-jdk18on", version.ref = "bcpkix-jdk18on" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }

[plugins]
android-library = { id = "com.android.library", version.ref = "android" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
